"""Puertos del núcleo comercial; no dependen de SQLite ni de la UI."""

from __future__ import annotations

from typing import Protocol, Sequence, runtime_checkable

from ..domain.models import (
    AdministrativeExitReasonRow,
    Article,
    Brand,
    Category,
    Supplier,
)


@runtime_checkable
class CatalogRepository(Protocol):
    def save_category(self, category: Category) -> Category: ...

    def get_category(self, category_id: str) -> Category | None: ...

    def list_categories(self, *, only_active: bool = True) -> Sequence[Category]: ...

    def save_brand(self, brand: Brand) -> Brand: ...

    def get_brand(self, brand_id: str) -> Brand | None: ...

    def list_brands(self, *, only_active: bool = True) -> Sequence[Brand]: ...

    def save_supplier(self, supplier: Supplier) -> Supplier: ...

    def get_supplier(self, supplier_id: str) -> Supplier | None: ...

    def list_suppliers(self, *, only_active: bool = True) -> Sequence[Supplier]: ...

    def save_article(self, article: Article) -> Article: ...

    def get_article(self, article_id: str) -> Article | None: ...

    def get_article_by_sku(self, sku: str) -> Article | None: ...

    def list_articles(self, *, only_active: bool = True) -> Sequence[Article]: ...

    def list_administrative_exit_reasons(
        self, *, only_active: bool = True
    ) -> Sequence[AdministrativeExitReasonRow]: ...
